@startuml authz-code-flow

actor "Resource Owner" as user
participant "User-Agent" as ua
participant "Client" as client
participant "Authoriztion Server" as authz
participant "Resource Server" as resource

user -> client : Resource Request
activate client

client -> client : Access Token?

alt invalid access token
  |||
  ua <-- client : Redirect to Authorization Endpoint
  deactivate client

  ua -> authz : Authorization Request
  note right : GET /authorize
  activate authz

  authz -> authz : User Authenticated ?

  alt unauthenticated
    |||
    ua <-- authz : Login Page
    deactivate authz
    activate ua

    user -> ua
    ua -> authz : Sign In
    deactivate ua
    activate authz

    authz -> authz : User Authentication
    |||
  end
  |||
  ua <-- authz : Approval Page
  deactivate authz
  activate ua

  user -> ua
  ua -> authz : Approved (or Denied)
  deactivate ua
  activate authz

  authz -> authz : Generate Authorization Code

  ua <-- authz : Redirect to Requested Redirect URI
  deactivate authz

  ua -> client : Authorization Response
  activate client

  client -> authz : Access Token Request
  note right : POST /token
  activate authz

  authz -> authz : Genereate Access Token (and Refresh Token)

  client <-- authz : Access Token Response
  deactivate authz
  |||
end
|||
client -> resource : Protected Resource Request
activate resource

alt use introspectio endpoint
  |||
  authz <- resource : Introspection Request
  note left : POST /introspect
  activate authz

  authz --> resource : Introspection Response
  deactivate authz
  |||
end
|||
client <-- resource : Protected Resource Response
deactivate resource

user <-- client : Resource Response
|||
@enduml authz-code-flow